#/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

export LICENSE_KEY='eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJDdXJpdHkgQUIiLCJzdWIiOiJDdXJpdHkgRGV2ZWxvcG1lbnQiLCJJZCI6IkxTNFNHenNKQUVtOUplS1BwQlRIVmprbHQ3SFhBbGVuIiwiUHJvZHVjdCI6IklkZW50aXR5IFNlcnZlciIsIlZlcnNpb24iOiI0LjAiLCJUaWVyIjoiU3Vic2NyaXB0aW9uIiwiR3JhY2UgUGVyaW9kIjoiNDUiLCJJc3N1ZSBEYXRlIjoiMjAyNC0xMi0xMiIsIkV4cGlyYXRpb24gRGF0ZSI6IjIwMjUtMTItMTIiLCJFZGl0aW9uIjoiQ3VzdG9tIiwiR3JvdXBzIjoiMyIsIkVudmlyb25tZW50IjoiVGVzdGluZyBDdXJpdHkgRGV2IiwiVHlwZSI6Ik5vbi1Qcm9kdWN0aW9uIiwiRmVhdHVyZXMiOlt7ImZlYXR1cmUiOiJwcm9maWxlcyIsInJlc3RyaWN0aW9ucyI6WyJhdXRoOmF1dGhlbnRpY2F0aW9uLXNlcnZpY2UiLCJhczpvYXV0aC1zZXJ2aWNlIiwidW06dXNlci1tYW5hZ2VtZW50LXNlcnZpY2UiLCJhcHBzOmFwcHMtc2VydmljZSIsInNpOnNhbWwtaWRwLXNlcnZpY2UiXX0seyJmZWF0dXJlIjoiYXV0aGVudGljYXRvcnMiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJkYXRhLXNvdXJjZXMiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJhbGFybXMiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJldmVudC1saXN0ZW5lcnMiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJhY3Rpb25zIiwicmVzdHJpY3Rpb25zIjpbXX0seyJmZWF0dXJlIjoiY2xhaW1zLXByb3ZpZGVycyIsInJlc3RyaWN0aW9ucyI6W119LHsiZmVhdHVyZSI6Im1ldHJpY3MiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJjbHVzdGVyIiwicmVzdHJpY3Rpb25zIjpbXX0seyJmZWF0dXJlIjoiaGFhcGkiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJkYXNoYm9hcmQiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJjcnlwdG8iLCJyZXN0cmljdGlvbnMiOlsiaHNtIl19LHsiZmVhdHVyZSI6InRva2VuLXByb2NlZHVyZS1wbHVnaW5zIiwicmVzdHJpY3Rpb25zIjpbXX0seyJmZWF0dXJlIjoiZGF0YWJhc2UtY2xpZW50cyIsInJlc3RyaWN0aW9ucyI6W119LHsiZmVhdHVyZSI6ImdyYXBocWwiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJnZW8iLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJiYWNrY2hhbm5lbC1hdXRoZW50aWNhdG9ycyIsInJlc3RyaWN0aW9ucyI6W119LHsiZmVhdHVyZSI6ImZpbmFuY2lhbC1ncmFkZSIsInJlc3RyaWN0aW9ucyI6W119LHsiZmVhdHVyZSI6Im11bHRpLXRlbmFuY3kiLCJyZXN0cmljdGlvbnMiOltdfSx7ImZlYXR1cmUiOiJhcHBsaWNhdGlvbnMiLCJyZXN0cmljdGlvbnMiOlsidG9rZW4taGFuZGxlciJdfV0sImlhdCI6MTczMzk2MTYwMCwibmJmIjoxNzMzOTYxNjAwLCJleHAiOjE3NjU0OTc2MDB9.grv98NluyB-w_i-DAYSy8uJEgbdLzn4BghsOyoEQY7gsqWa9yzNoBFPATrAV9KhJtx5nmU2qWUD_dGMNDvFOzWP-la9mwo0zc2R7Np0lwCZTH1mqG8BZefN3NBX35o1dO1B_Cesb5aQm4oqyGhd_Iledvezffa6p95AQ-5H6hmiChQDnX5NJuiRY6LsERYeStv8Zxh2RB2QNKdYa1nA-2p4AmZb-Hlmk3cMJZWx0ERd4VvZ8aUVtQCJtYUOUtwfGCb1SEBj_i2nRamrpiXzmeTnH53MN6dHuJVSBZuhSdraeTiBY6vgjKMI8m_Ho5pLo_pvtH8Wbz-PwmVBoV-NI4A'

#
# Manage license details
#
if [ "$LICENSE_KEY" == '' ]; then

  if [ "$LICENSE_FILE_PATH" == '' ]; then
    echo 'Please provide a LICENSE_FILE_PATH environment variable'
    exit 1
  fi

  export LICENSE_KEY=$(cat $LICENSE_FILE_PATH | jq -r .License)
  if [ "$LICENSE_KEY" == '' ]; then
    echo 'An invalid license file was provided for the Curity Identity Server'
    exit 1
  fi
fi

#
# Then run the deployment
#
docker compose up
